[package]
name = "RulesEngine"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.29.0"
bimap = "0.6.3"
grapher = "0.2.2"
rand = "0.8.5"
petgraph = "0.6.5"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
